language: node_js
node_js:
  - "node"
addons:
  code_climate:
    repo_token: 8d10d6cde56517aeddfa424ac22bd46d319dc75a86570077a690a2f6ef51f92f
script: npm run build
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./reports/coverage/lcov.info
